### ISSUE TITLE
Error: Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by IbrahimEzat** [codezero-be/laravel-localizer#1]
Hello, thanks for this laravel contribution but it gives an error with Laravel 7.X " ErrorException Invalid argument supplied for foreach()  " and pointing to the file odezero/laravel-localizer/src/Localizer.php:51  the detect() method

**Comment by ivanvermeyen** [comment]
Hello,

The `ServiceProvider` registers the `Localizer` class with the detectors array from the config file.
The `foreach` loops over these detectors...
Are the detectors not being injected properly?
