### ISSUE TITLE
UrlDetector broken when using Laravel Localized Routes omit_url_prefix_for_locale

### ISSUE THREAD

**Issue by zepfietje** [codezero-be/laravel-localizer#5]
The `UrlDetector` doesn't seem to work when using the `omit_url_prefix_for_locale` config option of the https://github.com/codezero-be/laravel-localized-routes package.

I created a custom `UrlDetector` class which works with above-mentioned package. However, it only works with that package, so I'm not sure what's the best way to go about fixing this issue.

```php
class UrlDetector implements Detector
{
    public function detect(): ?string
    {
        return Route::current()->getAction('localized-routes-locale');
    }
}
```

**Comment by ivanvermeyen** [comment]
Hi,

Can you. give me a more detailed example of what you are trying to do?
The localized routes package should already detect the custom route action attribute.

**Comment by zepfietje** [comment]
When detecting the locale from the URL, it will get the locale from the configured URL segment:

```php
public function detect()
{
    $position = Config::get('localizer.url-segment');

    return Request::segment($position);
}
```

However, when using `omit_url_prefix_for_locale` for a certain locale, it can't be detected using the default `UrlDetector`, since the locale is not present in the URL segment.

> The localized routes package should already detect the custom route action attribute.

I'm not sure what you mean, or am I missing something?

**Comment by ivanvermeyen** [comment]
The reason I didn't make a detector for this is that this package is optional in the localized routes package and this package can be used separately.

Instead, I check for the route action in the [middleware of the localized routes package](https://github.com/codezero-be/laravel-localized-routes/blob/c18bf4bf47be132d12cd67bfe17d2bffa3b63835/src/Middleware/SetLocale.php#L25).

Only if this action is not present will it run through the other detectors (if the option is enabled).

**Comment by zepfietje** [comment]
Ah, my fault. Totally understand it now!

Probably makes sense to merge the two packages to avoid confusion (like you already proposed https://github.com/codezero-be/laravel-localized-routes/issues/22).

Thanks for creating these awesome packages!

**Comment by ivanvermeyen** [comment]
No problem, I agree, it's confusing, and I'd like to simplify some things in the future. 👌
